apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  database-url: "postgresql://username:password@ecommerce-prod-postgres.postgres.database.azure.com:5432/userdb"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials  
type: Opaque
stringData:
  connection-string: "mongodb://ecommerce-prod-mongodb:key@ecommerce-prod-mongodb.mongo.cosmos.azure.com:10255/productdb?ssl=true"
