apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
    
    - job_name: 'deployment-metrics'
      static_configs:
      - targets: ['api-gateway:3000', 'user-service:3000', 'product-service:3000', 'order-service:3000']
    
    rule_files:
    - "/etc/prometheus/rules/*.yml"

  deployment-rules.yml: |
    groups:
    - name: deployment.rules
      rules:
      - alert: DeploymentFailed
        expr: increase(kube_deployment_status_replicas_unavailable[5m]) > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Deployment {{ $labels.deployment }} failed"
          description: "{{ $labels.deployment }} has unavailable replicas"
      
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
